extends Node


func family_name(c: Variant) -> String:
	match c:
		Tower.Family.Spider: return "Spider"
		Tower.Family.Skeleton: return "Skeleton"
		Tower.Family.Ghost: return "Ghost"
		Tower.Family.Pumpkin: return "Pumpkin"
		_: return "-"


func tower_name(type: Tower.Type) -> String:
	match type:
		Tower.Type.S1_1: return "Spidey"
		Tower.Type.S1_2: return "Deathspidey"
		Tower.Type.S2_1: return "Venomcharge"
		Tower.Type.S2_2: return "Venomleech"
		Tower.Type.S3_1: return "Weblurker"
		Tower.Type.S3_2: return "Necroweb"
		Tower.Type.S4_1: return "Widowbane"
		Tower.Type.S4_2: return "Widowboost"
		Tower.Type.K1_1: return "Ribcage"
		Tower.Type.K1_2: return "Ribblade"
		Tower.Type.K2_1: return "Bonecrusher"
		Tower.Type.K2_2: return "Bonekeeper"
		Tower.Type.K3_1: return "Cursedmarrow"
		Tower.Type.K3_2: return "Marrowbinder"
		Tower.Type.K4_1: return "Elderskull"
		Tower.Type.K4_2: return "Skullbane"
		Tower.Type.G1_1: return "Ghosty"
		Tower.Type.G1_2: return "Shyghost"
		Tower.Type.G2_1: return "Shadowpiercer"
		Tower.Type.G2_2: return "Shadowfighter"
		Tower.Type.G3_1: return "Sneakyspecter"
		Tower.Type.G3_2: return "Omnispecter"
		Tower.Type.G4_1: return "Shinyphantom"
		Tower.Type.G4_2: return "Greatphantom"
		Tower.Type.P1_1: return "Baby Boo"
		Tower.Type.P1_2: return "Baby Bear"
		Tower.Type.P2_1: return "Cinderella"
		Tower.Type.P2_2: return "Goosebumps"
		Tower.Type.P3_1: return "Lakota"
		Tower.Type.P3_2: return "Crystal Star"
		Tower.Type.P4_1: return "Musquee"
		Tower.Type.P4_2: return "Big Max"
		Tower.Type.COIN: return "Bag of Coins"
		Tower.Type.ROCK: return "Rock"
		Tower.Type.BOMB: return "Bomb"
		Tower.Type.MIRROR: return "Mirror"
		_: return "???"


func debug_name(tower: Tower) -> String:
	return ("ally" if tower.team == 0 else "enemy") + " " + tower_name(tower.type)


func tower_trigger(type: Tower.Type) -> String:
	match type:
		Tower.Type.S1_1: return ""
		Tower.Type.S1_2: return "When killed"
		Tower.Type.S2_1: return "Fight start"
		Tower.Type.S2_2: return ""
		Tower.Type.S3_1: return "Adjacent spider killed"
		Tower.Type.S3_2: return "When killed"
		Tower.Type.S4_1: return "Fight start"
		Tower.Type.S4_2: return "Adjacent minion boosted"
		Tower.Type.K1_1: return ""
		Tower.Type.K1_2: return "When killed"
		Tower.Type.K2_1: return "When hitting an enemy"
		Tower.Type.K2_2: return ""
		Tower.Type.K3_1: return "Adjacent minion killed"
		Tower.Type.K3_2: return ""
		Tower.Type.K4_1: return "After gaining stats"
		Tower.Type.K4_2: return "Fight start"
		Tower.Type.G1_1: return ""
		Tower.Type.G1_2: return "Fight start"
		Tower.Type.G2_1: return "Adjacent ghost becomes ghostly"
		Tower.Type.G2_2: return "When killed"
		Tower.Type.G3_1: return "Adjacent minion killed"
		Tower.Type.G3_2: return "Fight start"
		Tower.Type.G4_1: return "Friendly ghost becomes ghostly"
		Tower.Type.G4_2: return "Friendly ghost becomes ghostly"
		Tower.Type.P1_1: return ""
		Tower.Type.P1_2: return ""
		Tower.Type.P2_1: return "Fight start"
		Tower.Type.P2_2: return "Fight start"
		Tower.Type.P3_1: return "Minion from the row shoots"
		Tower.Type.P3_2: return "Friendly ghost becomes ghostly"
		Tower.Type.P4_1: return "When hit"
		Tower.Type.P4_2: return "Friendly minion killed"
		Tower.Type.COIN: return "When killed"
		Tower.Type.ROCK: return ""
		Tower.Type.BOMB: return ""
		Tower.Type.MIRROR: return ""
		_: return ""


func tower_effect(type: Tower.Type) -> String:
	match type:
		Tower.Type.S1_1: return ""
		Tower.Type.S1_2: return "Gain +1 HP permanently. "
		Tower.Type.S2_1: return "Gives +1 +1 to the row."
		Tower.Type.S2_2: return "Boosts received by the adjacent spiders are permanent."
		Tower.Type.S3_1: return "Gains +1 +1 permanently."
		Tower.Type.S3_2: return "Gives +2 HP permanently to the row."
		Tower.Type.S4_1: return "Destroys the friendly spider above and gain their stats permanently."
		Tower.Type.S4_2: return "Gains the same boost."
		Tower.Type.K1_1: return ""
		Tower.Type.K1_2: return "Gains +1 ATK permanently."
		Tower.Type.K2_1: return "Gives -1 ATK."
		Tower.Type.K2_2: return ""
		Tower.Type.K3_1: return "Shoots."
		Tower.Type.K3_2: return "All received ATK boosts are permanent."
		Tower.Type.K4_1: return "Shoots."
		Tower.Type.K4_2: return "Doubles its ATK."
		Tower.Type.G1_1: return ""
		Tower.Type.G1_2: return "Gains ghostly."
		Tower.Type.G2_1: return "Shoots."
		Tower.Type.G2_2: return "Gives ghostly to adjacent ghosts."
		Tower.Type.G3_1: return "Gains ghostly."
		Tower.Type.G3_2: return "Gains half the stats of the friendly minion above."
		Tower.Type.G4_1: return "Gives +1 +2 permanently."
		Tower.Type.G4_2: return "Gains +2 +1 permanantly."
		Tower.Type.P1_1: return ""
		Tower.Type.P1_2: return "Received HP boosts are permanent."
		Tower.Type.P2_1: return "This minion and adjacent ones get +1 +1 for the fight."
		Tower.Type.P2_2: return "Gives +1 HP permanently to the row."
		Tower.Type.P3_1: return "Gives +1 ATK."
		Tower.Type.P3_2: return "Gives +1 +1."
		Tower.Type.P4_1: return "Gives as much ATK to adjacent minions."
		Tower.Type.P4_2: return "Gives +2 ATK permanently."
		Tower.Type.COIN: return "Gives +1 coin in the next shop."
		Tower.Type.ROCK: return "Can't gain ATK."
		Tower.Type.BOMB: return "Only shoots when destroyed."
		Tower.Type.MIRROR: return "Can't gain ATK. Reflects shots."
		_: return ""
