extends Node


func family_name(c: Variant) -> String:
	match c:
		Tower.Family.Spider: return "Spider"
		Tower.Family.Skeleton: return "Skeleton"
		Tower.Family.Ghost: return "Ghost"
		Tower.Family.Pumpkin: return "Pumpkin"
		_: return "–"


func tower_name(type: Tower.Type) -> String:
	match type:
		Tower.Type.S1_1: return "S1_1"
		Tower.Type.S1_2: return "S1_2"
		Tower.Type.S2_1: return "S2_1"
		Tower.Type.S2_2: return "S2_2"
		Tower.Type.S3_1: return "S3_1"
		Tower.Type.S3_2: return "S3_2"
		Tower.Type.S4_1: return "S4_1"
		Tower.Type.S4_2: return "S4_2"
		Tower.Type.K1_1: return "K1_1"
		Tower.Type.K1_2: return "K1_2"
		Tower.Type.K2_1: return "K2_1"
		Tower.Type.K2_2: return "K2_2"
		Tower.Type.K3_1: return "K3_1"
		Tower.Type.K3_2: return "K3_2"
		Tower.Type.K4_1: return "K4_1"
		Tower.Type.K4_2: return "K4_2"
		Tower.Type.G1_1: return "G1_1"
		Tower.Type.G1_2: return "G1_2"
		Tower.Type.G2_1: return "G2_1"
		Tower.Type.G2_2: return "G2_2"
		Tower.Type.G3_1: return "G3_1"
		Tower.Type.G3_2: return "G3_2"
		Tower.Type.G4_1: return "G4_1"
		Tower.Type.G4_2: return "G4_2"
		Tower.Type.P1_1: return "P1_1"
		Tower.Type.P1_2: return "P1_2"
		Tower.Type.P2_1: return "P2_1"
		Tower.Type.P2_2: return "P2_2"
		Tower.Type.P3_1: return "P3_1"
		Tower.Type.P3_2: return "P3_2"
		Tower.Type.P4_1: return "P4_1"
		Tower.Type.P4_2: return "P4_2"
		_: return "???"


func tower_trigger(type: Tower.Type) -> String:
	match type:
		Tower.Type.S1_1: return ""
		Tower.Type.S1_2: return "When killed"
		Tower.Type.S2_1: return "Tower from the row gains HP"
		Tower.Type.S2_2: return "When built"
		Tower.Type.S3_1: return "Adjacent spider killed"
		Tower.Type.S3_2: return "Tower above/below gains HP"
		Tower.Type.S4_1: return ""
		Tower.Type.S4_2: return "Adjacent tower boosted"
		Tower.Type.K1_1: return ""
		Tower.Type.K1_2: return "When killed"
		Tower.Type.K2_1: return ""
		Tower.Type.K2_2: return "When built"
		Tower.Type.K3_1: return "Adjacent tower killed"
		Tower.Type.K3_2: return ""
		Tower.Type.K4_1: return "After gaining stats"
		Tower.Type.K4_2: return "Fight start"
		Tower.Type.G1_1: return ""
		Tower.Type.G1_2: return "When hit"
		Tower.Type.G2_1: return "Adjacent tower becomes ghostly"
		Tower.Type.G2_2: return "When killed"
		Tower.Type.G3_1: return "Adjacent tower killed"
		Tower.Type.G3_2: return "Fight start"
		Tower.Type.G4_1: return ""
		Tower.Type.G4_2: return "Friendly tower becomes ghostly"
		Tower.Type.P1_1: return ""
		Tower.Type.P1_2: return ""
		Tower.Type.P2_1: return "Fight start"
		Tower.Type.P2_2: return "Friendly pumpkin killed"
		Tower.Type.P3_1: return "Tower from the row shoots"
		Tower.Type.P3_2: return "Friendly tower becomes ghostly"
		Tower.Type.P4_1: return "When hit"
		Tower.Type.P4_2: return ""
		_: return ""


func tower_effect(type: Tower.Type) -> String:
	match type:
		Tower.Type.S1_1: return ""
		Tower.Type.S1_2: return "Gain +1 HP permanently. "
		Tower.Type.S2_1: return "Gives +1 ATK."
		Tower.Type.S2_2: return "Choose a tower, this steals 2 ATK to it."
		Tower.Type.S3_1: return "Gains +1 +1 permanently."
		Tower.Type.S3_2: return "Gives the same amount of ATK."
		Tower.Type.S4_1: return "Can hit allies. Gains friendly spiders stats permanently."
		Tower.Type.S4_2: return "Gains the same boost."
		Tower.Type.K1_1: return ""
		Tower.Type.K1_2: return "Gains +1 ATK permanently."
		Tower.Type.K2_1: return "Shoots twice."
		Tower.Type.K2_2: return "Gains +1 ATK for each friendly skeleton."
		Tower.Type.K3_1: return "Shoots."
		Tower.Type.K3_2: return "Can hit allies. Gives them +2 HP permanently."
		Tower.Type.K4_1: return "Shoots."
		Tower.Type.K4_2: return "Doubles its ATK."
		Tower.Type.G1_1: return ""
		Tower.Type.G1_2: return "Gains ghostly."
		Tower.Type.G2_1: return "Shoots."
		Tower.Type.G2_2: return "Gives ghostly to adjacent ghosts."
		Tower.Type.G3_1: return "Gains ghostly."
		Tower.Type.G3_2: return "Gains the stats of the friendly tower above."
		Tower.Type.G4_1: return "Always has the sum of adjacent towers stats."
		Tower.Type.G4_2: return "Gains +1 +1 permanantly."
		Tower.Type.P1_1: return ""
		Tower.Type.P1_2: return "Received HP boosts are permanent."
		Tower.Type.P2_1: return "This tower and adjacent ones get +1 +1 for the fight."
		Tower.Type.P2_2: return "The killed pumpkin shoots."
		Tower.Type.P3_1: return "Gives +1 ATK."
		Tower.Type.P3_2: return "Gives +1 ATK and HP."
		Tower.Type.P4_1: return "Gives as much ATK to adjacent towers."
		Tower.Type.P4_2: return "Gives +2 ATK permanently."
		Tower.Type.ROCK: return "Can't gain ATK."
		Tower.Type.MIRROR: return "Can't gain ATK. Reflects shots."
		_: return ""
